var coords = [];
coords.push(123);
coords.push(123);
coords.push(143);
coords.push(149);
coords.push(149);
coords.push(129);
var usernames = [];
usernames.push("Teste");
usernames.push("Teste");
usernames.push("Teste");
usernames.push("Teste");
